### ISSUE TITLE
unable to run 

### ISSUE THREAD

**Issue by suvraroy** [dctremblay/Project-Rescue#1]
migrate.py giving me error
initializing migration process
importing global instance structure
migrating primary key sequences to safe values
Traceback (most recent call last):
  File "./migrate.py", line 12, in <module>
    if not migrate.run(project_identifier):
  File "/root/Project-Rescue/lib/migrate.py", line 44, in run
    instance()
  File "/root/Project-Rescue/lib/migrate.py", line 122, in instance
    pkeys()
  File "/root/Project-Rescue/lib/migrate.py", line 165, in pkeys
    orm.set_sequence_value(cn['dst'], table, newseq + 1)
  File "/root/Project-Rescue/lib/orm.py", line 94, in set_sequence_value
    execute(conn, q)
UnboundLocalError: local variable 'q' referenced before assignment

using DB mysql to mysql

**Comment by dctremblay** [comment]
@suvraroy Which version do you use to execute the script ?

**Comment by suvraroy** [comment]
@dctremblay 
using python 3.6

**Comment by dctremblay** [comment]
@suvraroy I checked quickly and I think that you could fix this with no problems.

```python
def set_sequence_value(conn, table, value):
    # works only under postgres for the moment
    if conn[TYPE] == 'postgresql':
        q = 'ALTER SEQUENCE {0}_id_seq RESTART WITH {1}'.format(table, value)
    try:
        execute(conn, q)
    except postgresql.ProgrammingError:
        pass
```

This would need a `if conn[TYPE] == 'mysql'` and the `q` should be variable that represent query to set the primary key value in a MySQL table.

After these 3 simple lines of code, I think that the script will run successfully.

Have a great day !

**Comment by dctremblay** [comment]
@suvraroy You can now test if it will work for you, someone submitted a pull request that implements MySQL (and probably fixes the problem that occured to you). Thank you very much and have a great day !

**Comment by suvraroy** [comment]
no its doesnt work .

**Comment by dctremblay** [comment]
@suvraroy Do you have a backtrace or something like this ? 

Thank you very much !
